name: ci-pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install -U pip
        python3 -m pip install poetry==1.6.1
        
    - name: Linting
      run: |
          poetry install
          poetry run isort .
          poetry run black .

    - name: Unittests
      run: |
        python3 -m unittest --verbose tests.test_extract tests.test_database